version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
      SECRET: e8a24534bd9c13412ac919164c989bc3
      DATABASE_URL: mysql://admin:secret@mysql:3306/ickle
    depends_on:
      - mysql
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ickle
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d